[workspace]

resolver = "2"

members = [
    "gui",
]

[workspace.package]
version = "0.1.0"

[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.bench]
debug = true

[workspace.dependencies]
rusty-hook = "0.11" # for dev/git hooks